grammar Pathology.XPath
  
  location_path     <- location_step+ <Pathology.LocationPath>
  
  location_step     <- axis test:node_test? <Pathology.LocationStep>
  
  axis              <- "/" axis_identifier <Pathology.Axis>
  
  axis_identifier   <- axis_name:[a-z\-]+ "::" / axis_shorthand
  
  axis_shorthand    <- "@" / ".." / "." / "/" / ""
  
  node_test         <- node_name <Pathology.NodeTest>
  
  node_name         <- [A-Za-z0-9\-]+
  
  
